all: true
check-coverage: true
include:
  - "src/**/*.js"
exclude:
  - "**/*.test.js"
report-dir: coverage
statements: 05
branches: 05
functions: 05
lines: 05
watermarks:
  statements:
    - 38
    - 90
  branches:
    - 38
    - 90
  functions:
    - 35
    - 90
  lines:
    - 39
    - 90
