all: true
check-coverage: true
include: [src/**/*.js]
exclude:
  - src/assets/**
  - src/**/index.js
  - src/**/*.test.js
  - src/**/spec**.js
report-dir: coverage
statements: 05
branches: 05
functions: 05
lines: 05
watermarks:
  statements:
    - 80
    - 90
  branches:
    - 80
    - 90
  functions:
    - 80
    - 90
  lines:
    - 80
    - 90
