name: Unit tests

on:
  workflow_call:
    inputs:
      coverage-report: { type: boolean, required: false, default: false }
      coverage-artifact: { type: string, required: false, default: coverage }
    outputs:
      coverage-artifact:
        value: ${{ inputs.coverage-artifact }}

concurrency:
  group: unit-tests-${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

permissions: {}

jobs:
  run-tests:
    name: Unit (Node ${{ matrix.node }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20]
    env:
      COVERAGE: ${{ matrix.node == 20 || null }}
    steps:
      - name: Run tests
        uses: govuk-one-login/github-actions/node/run-script@4616241694c035be4ea4a10fc0fe6521c0f079f8
        with:
          node-version: ${{ matrix.node }}.x
          script: npm run test"${COVERAGE:+:coverage}"

      - name: Archive coverage results
        if: ${{ inputs.coverage-report && env.COVERAGE }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.coverage-artifact }}
          retention-days: 3
          path: coverage/lcov.info
